type Bookmark {
    id: Int!
    title: String!
    url: String!
    description: String
    createdDate: Date!
    folderId: Int
}
input CreateBookmarkInput {
    title: String!
    url: String!
    description: String
    folderId: Int
}

input UpdateBookmarkInput {
    id: Int!
    title: String
    description: String
    url: String
    folderId: Int
}

union BookmarkResult = BaseError | Bookmark

type Query {
    bookmark(id: Int!): BookmarkResult! @auth
}

type Mutation {
    createBookmark(data: CreateBookmarkInput!): BookmarkResult! @auth
    updateBookmark(data: UpdateBookmarkInput!): BookmarkResult! @auth
}
