type Folder {
    id: Int!
    parent: Folder
    children: [Folder]!
    bookmarks: [Bookmark]!
    depth: Int!
    name: String!
}

union FolderResult = BaseError | Folder

input CreateFolderInput {
    name: String!
    parentId: Int
}

type Query {
    folder(id: Int!): FolderResult!
    q: Folder
}

type Mutation {
    createFolder(data: CreateFolderInput!): FolderResult! @auth
    updateFolderName(id: Int!, name: ID!): FolderResult! @auth
    softDeleteFolder(id: Int!): FolderResult! @auth
    recoverFolder(id: Int!): FolderResult! @auth
    moveFolder(folderId: Int!, targetFolderId: Int!): FolderResult! @auth
    deleteFolder(id: Int!): FolderResult! @auth
}
