type Category {
    id: ID!
    name: String!
    bookmarks: [Bookmark]!
}

input CreateCategoryInput {
    name: String!
    bookmarks: [Int!]
}

type DeleteCategoryResult {
    category: Category
    errors: [BaseError]
}

type Mutation {
    createCategory(data: CreateCategoryInput!): Category
    "Pass in category id"
    deleteCategory(id: Int!): Boolean!
}
