type Category {
    id: ID!
    name: String!
    bookmarks: [Bookmark]!
}

input CreateCategoryInput {
    name: String!
    bookmarks: [Int!]
}

type NoErrorCategoryDeletion {
    success: Boolean!
}

union CreateCategoryResult = BaseError | Category
union DeleteCategoryResult = BaseError | NoErrorCategoryDeletion

type Mutation {
    createCategory(data: CreateCategoryInput!): CreateCategoryResult!
    "Pass in category id"
    deleteCategory(id: Int!): DeleteCategoryResult!
}
