name: Run tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Install dependencies
        run: npm install
        working-directory: ./packages/web
      - name: Run tests
        run: npm test
        working-directory: ./packages/web
